apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: #labels cana also be added to service
    group: example
spec:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
--- #TO seperate the yaml file we need only these dashed as seperator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels: #labels cana also be added
    group: example
spec:
  replicas: 1
  selector:
    matchExpressions:
      - {key: app, operator: In,values: [second-app, first-app]}
    #matchExpressions:
    #  - {key: app, operator: NotIn,values: [second-app, first-app]}
    #matchLabels:
    #  app: second-app
    #  tier: backend
  template:
    metadata: 
      labels:
        app: second-app
        tier: backend
    spec: 
      containers:
        - name: second-node
          image: academind/kub-first-app:2
        # - name: ...
        #   image: ...
